import { atom } from "recoil";
import { recoilPersist } from "recoil-persist";
import Objective from "./Objective";
import Stratagem from "./Stratagem";

// this allows the atom to be persisted in local storage
const { persistAtom } = recoilPersist();

// export the atom for storing all possible missions
export const abilitiesState = atom<Mission[]>({
    key: 'missionlist',
    default: [],
    effects_UNSTABLE: [ persistAtom ]
});

/**
 *  An interface describing an missions data. A missions contains out of 
 */
export default interface Mission {

    // The id of the mission. It's generated by the application.
    id:string;

    // The name of the mission.
    name:string;

    // the points limit for one size
    points:number;

    // the board size for the game.
    board:string;

    // The rules of the mission.
    rules:string;

    // The stratagems that players have access to when they play this mission.
    stratagems:Array<Stratagem>;

    // The objectives of this mission.
    objectives:Array<Objective>;
};
