/**
 *  An interface describing an objective.
 */
export default interface Objective {

    // The id of the objective. It's generated by the application.
    id:string;

    // The name of the objective.
    name:string;

    // The rules of the objective.
    rules:string;

};